# .air.toml
root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/bot ./cmd/bot/main.go" # Adjust path to your main package
bin = "tmp/bot"
full_bin = ""
args = []
env = []
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_file = []
exclude_regexp = ["_test.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "env"]
stop_on_error = true
log = "build-errors.log"

[run]
cmds = []
delay = 1000 # milliseconds
stop_on_error = true

[misc]
clean_on_exit = true