services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: discordbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: .
      target: dev
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app

volumes:
  db_data:
